### ISSUE TITLE
Wrong behavior of ᵗ according to Wiki

### ISSUE THREAD

**Issue by MichaelChat** [cairdcoinheringaahing/Whispers#2]
In the table with [Infix commands](https://github.com/cairdcoinheringaahing/Whispers/wiki/List-of-commands#infix-commands) it says under `ᵗ`:  

> Last R elements of L

After briefly browsing the source code, I think it should rather say: **Drop the first R elements of L**
Here is a little [code snippet](https://tio.run/##K8/ILC5ILSr@/99OQSkxKTklVYnLTsGQyw5IPNw63YiLy7WiIDW5JDVFQQkkZafgX1pSUFqiYPz/PwA) of what I had tried to do.

**Comment by cairdcoinheringaahing** [comment]
In order to avoid changing existing behaviour, the description of the `ᵗ` command has been changed in the wiki and the `ˡ` command has been added with the "Last R elements of L" behaviour.
